export const productDemoData = [
  {
    id: 1,
    imageUrl: require('../assets/images/braile-black.png'),
    productTitle: 'Braille Trench Jacket',
    productSubtitle: 'Color Variant',
    price: 360,
    newArrival: true,
  },
  {
    id: 2,
    imageUrl: require('../assets/images/sacred.png'),
    productTitle: 'Sacred Heart Cut T-shirt',
    productSubtitle: 'Red',
    price: 60,
    newArrival: true,
  },
  {
    id: 3,
    imageUrl: require('../assets/images/frowny.png'),
    productTitle: 'Frowny Face Cut T-shirt',
    productSubtitle: 'Black',
    price: 60,
    newArrival: true,
  },
  {
    id: 4,
    imageUrl: require('../assets/images/tie-and-die.png'),
    productTitle: 'Tie & Die Sweatpants',
    productSubtitle: 'Yellow/Blue',
    price: 100,
    newArrival: true,
  },
  {
    id: 5,
    imageUrl: require('../assets/images/navy-thermal.png'),
    productTitle: 'Navy Thermal Lined Zip Up',
    productSubtitle: 'Blue',
    price: 100,
    newArrival: true,
  },
];
